### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MattiasGees** [jetstack/google-cas-issuer#21]
I am running into the following issue when trying to issue a certificate

```
E0201 13:26:07.800596       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 263 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x187ee60, 0x27ed950)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:48 +0x89
panic(0x187ee60, 0x27ed950)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/jetstack/google-cas-issuer/pkg/controller/certificaterequest.(*CertificateRequestReconciler).Reconcile(0xc0002bf6e0, 0x1cdd760, 0xc00060af60, 0xc000722780, 0xa, 0xc0002b1700, 0x16, 0xc00060af00, 0x0, 0x0, ...)
	/workspace/pkg/controller/certificaterequest/certificaterequest_controller.go:158 +0xb58
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003405a0, 0x1cdd6a0, 0xc0000aa480, 0x18f0860, 0xc00000d8e0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003405a0, 0x1cdd6a0, 0xc0000aa480, 0xc00052fd00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1cdd6a0, 0xc0000aa480)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00052ff50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000755f50, 0x1ca0a00, 0xc00060ab70, 0xc0000aa401, 0xc000101c80)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00052ff50, 0x3b9aca00, 0x0, 0x3b9aca01, 0xc000101c80)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1cdd6a0, 0xc0000aa480, 0xc000610100, 0x3b9aca00, 0x0, 0x10000c000051c01)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1cdd6a0, 0xc0000aa480, 0xc000610100, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:208 +0x4de
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16febf8]

goroutine 263 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x187ee60, 0x27ed950)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/jetstack/google-cas-issuer/pkg/controller/certificaterequest.(*CertificateRequestReconciler).Reconcile(0xc0002bf6e0, 0x1cdd760, 0xc00060af60, 0xc000722780, 0xa, 0xc0002b1700, 0x16, 0xc00060af00, 0x0, 0x0, ...)
	/workspace/pkg/controller/certificaterequest/certificaterequest_controller.go:158 +0xb58
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003405a0, 0x1cdd6a0, 0xc0000aa480, 0x18f0860, 0xc00000d8e0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003405a0, 0x1cdd6a0, 0xc0000aa480, 0xc00052fd00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1cdd6a0, 0xc0000aa480)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00052ff50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000755f50, 0x1ca0a00, 0xc00060ab70, 0xc0000aa401, 0xc000101c80)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00052ff50, 0x3b9aca00, 0x0, 0x3b9aca01, 0xc000101c80)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1cdd6a0, 0xc0000aa480, 0xc000610100, 0x3b9aca00, 0x0, 0x10000c000051c01)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1cdd6a0, 0xc0000aa480, 0xc000610100, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:208 +0x4de
```

I deployed the latest image and had the following code:

```
apiVersion: cas-issuer.jetstack.io/v1alpha1
kind: GoogleCASIssuer
metadata:
  name: googlecasissuer
  namespace: google-cas
spec:
  project: <google-project>
  location: europe-west1
  certificateAuthorityID: <certificate-name>
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-certificate
  namespace: google-cas
spec:
  secretName: demo-tls
  dnsNames:
    - google-cas.example.net
  commonName: google-cas.example.net
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASIssuer
    name: googlecasissuer
```

**Comment by jakexks** [comment]
Fixed in v0.1.1
